# Generated by Django 5.0 on 2024-03-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_prof_union',
            field=models.BooleanField(default=False, verbose_name='Является профсоюзом'),
        ),
    ]
