# Generated by Django 5.0 on 2024-07-02 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discontcard', '0001_initial'),
        ('users', '0007_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='discont_card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discontcard.discontcard', verbose_name='Пользователь карты'),
        ),
    ]
