# Generated by Django 5.0 on 2024-01-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название новости')),
                ('text', models.TextField(verbose_name='Тело статьи')),
                ('date_create', models.DateField(auto_now=True, verbose_name='Дата создания')),
                ('data_update', models.DateField(auto_now=True, verbose_name='Дата обновления')),
            ],
        ),
    ]
