# Generated by Django 5.0 on 2024-01-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_options_alter_post_data_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_update',
            field=models.DateTimeField(verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_create',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
    ]
