# Generated by Django 5.0 on 2024-02-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_data_update_alter_post_date_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='Опубликованно'),
        ),
    ]
