# Generated by Django 5.0 on 2024-07-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscontCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField(unique=True, verbose_name='Номер скидочной карты')),
                ('data_creation', models.DateField(auto_now=True, verbose_name='Дата создания')),
                ('procent', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Процент скидки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус карты')),
            ],
            options={
                'verbose_name': 'Дисконтная Карта',
                'verbose_name_plural': 'Дисконтные Карты',
            },
        ),
    ]
